#Define JWT manualmente
@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTVkMWY2ZmE4OWRlZDNmNzBlZWQwMmQiLCJpYXQiOjE3Njc3MTIwMjIsImV4cCI6MTc2NzcxOTIyMn0.MCoxHykaPyGCST3VZEfad-wLkiAkUXEYXEGFtlAEROY

GET http://localhost:3000/api/v1/sondas HTTP/1.1
Authorization: Bearer {{JWT}}

###

GET http://localhost:3000/api/v1/sondas/6907b94195c652f153e657d3 HTTP/1.1
Authorization: Bearer {{JWT}}

###

POST http://localhost:3000/api/v1/sondas HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
    "nombreSonda": "Sonda # 1",
    "descripcionSonda": "Prueba de descripción",
    "localizacion": "Madrid"
}

###
PUT http://localhost:3000/api/v1/sondas/6907b94195c652f153e657d3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
    "nombreSonda": "Sonda # 6",
    "descripcionSonda": "Prueba de descripción",
    "localizacion": "Valladolid"
}

###
DELETE http://localhost:3000/api/v1/sondas/6907b94195c652f153e657d3 HTTP/1.1
Authorization: Bearer {{JWT}}

###